In [1]:
import pandas as pd
import os

In [2]:
train_df = pd.read_csv(os.path.abspath('../input/cleaned-featured-2008-2017.csv'))

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26101 entries, 0 to 26100
Data columns (total 34 columns):
p_fs                        26101 non-null float64
p_w1sp                      26101 non-null float64
p_w2sp                      26101 non-null float64
p_wrp                       26101 non-null float64
p_tpw                       26101 non-null float64
p_tmw                       26101 non-null float64
p_aces_per_game             26101 non-null float64
p_df_per_game               26101 non-null float64
p_bp_won                    26101 non-null float64
p_wsp                       26101 non-null float64
p_completeness              26101 non-null float64
p_serve_adv                 26101 non-null float64
p_number_of_matches_used    26101 non-null int64
o_fs                        26101 non-null float64
o_w1sp                      26101 non-null float64
o_w2sp                      26101 non-null float64
o_wrp                       26101 non-null float64
o_tpw                       26101 non-null float64
o_tmw                       26101 non-null float64
o_aces_per_game             26101 non-null float64
o_df_per_game               26101 non-null float64
o_bp_won                    26101 non-null float64
o_wsp                       26101 non-null float64
o_completeness              26101 non-null float64
o_serve_adv                 26101 non-null float64
direct                      26101 non-null float64
o_number_of_matches_used    26101 non-null int64
player_id                   26101 non-null int64
opponent_id                 26101 non-null int64
tournament_name             26101 non-null object
date                        26101 non-null object
player_elo_rating           26101 non-null int64
opponent_elo_rating         26101 non-null int64
p_matches                   26101 non-null int64
dtypes: float64(25), int64(7), object(2)
memory usage: 6.8+ MB

In [4]:
train_df['fs_diff'] = train_df['p_fs'] - train_df['o_fs']
train_df['w1sp_diff'] = train_df['p_w1sp'] - train_df['o_w1sp']
train_df['w2sp_diff'] = train_df['p_w2sp'] - train_df['o_w2sp']
train_df['wrp_diff'] = train_df['p_wrp'] - train_df['o_wrp']
train_df['tpw_diff'] = train_df['p_tpw'] - train_df['o_tpw']
train_df['tmw_diff'] = train_df['p_tmw'] - train_df['o_tmw']
train_df['aces_per_game_diff'] = train_df['p_aces_per_game'] - train_df['o_aces_per_game']
train_df['df_per_game_diff'] = train_df['p_df_per_game'] - train_df['o_df_per_game']
train_df['bp_won_diff'] = train_df['p_bp_won'] - train_df['o_bp_won']
train_df['wsp_diff'] = train_df['p_wsp'] - train_df['o_wsp']
train_df['completeness_diff'] = train_df['p_completeness'] - train_df['o_completeness']
train_df['serve_adv_diff'] = train_df['p_serve_adv'] - train_df['o_serve_adv']
train_df['elo_rating_diff'] = train_df['player_elo_rating'] - train_df['opponent_elo_rating']

In [5]:
train_df.head()

,p_fs,p_w1sp,p_w2sp,p_wrp,p_tpw,p_tmw,p_aces_per_game,p_df_per_game,p_bp_won,p_wsp,...,wrp_diff,tpw_diff,tmw_diff,aces_per_game_diff,df_per_game_diff,bp_won_diff,wsp_diff,completeness_diff,serve_adv_diff,elo_rating_diff
0,0.591613,0.779391,0.526186,0.675453,0.675630,0.479452,0.998942,0.165079,0.652812,0.675985,...,-0.014547,0.000603,0.098500,0.553598,0.007185,0.086272,0.030802,0.011420,0.016256,149
1,0.630058,0.688413,0.515046,0.685150,0.664963,0.525424,0.244813,0.147994,0.627497,0.624277,...,-0.001544,-0.006851,-0.038679,-0.077867,-0.003552,0.035205,-0.017070,-0.012686,-0.018614,-48
2,0.605263,0.633270,0.533333,0.688475,0.655906,0.416667,0.356589,0.155039,0.592357,0.593822,...,-0.017311,-0.024430,-0.077160,0.106839,-0.004801,0.036616,-0.034637,-0.034726,-0.051948,-217
3,0.626886,0.723634,0.523398,0.686482,0.674041,0.535211,0.484425,0.204082,0.589633,0.648924,...,0.011324,0.010331,-0.000503,-0.113705,-0.005531,-0.002420,0.008312,0.012960,0.019636,133
4,0.583093,0.698630,0.480043,0.682102,0.656523,0.500000,0.394469,0.292576,0.587179,0.607499,...,-0.011240,-0.028000,-0.043860,-0.287621,0.061233,0.004098,-0.058925,-0.047684,-0.070165,-209

In [6]:
train_df = train_df.drop(['p_fs', 'o_fs', 'p_w1sp','o_w1sp','p_w2sp','o_w2sp','p_wrp','o_wrp','p_tpw','o_tpw','p_tmw','o_tmw','p_aces_per_game','o_aces_per_game'
               ,'p_df_per_game','o_df_per_game','p_bp_won','o_bp_won','p_wsp','o_wsp','p_completeness','o_completeness','p_serve_adv','o_serve_adv','player_elo_rating','opponent_elo_rating'], axis = 1)

In [14]:
train_df.columns.values

array(['p_number_of_matches_used', 'direct', 'o_number_of_matches_used',
       'player_id', 'opponent_id', 'tournament_name', 'date', 'p_matches',
       'fs_diff', 'w1sp_diff', 'w2sp_diff', 'wrp_diff', 'tpw_diff',
       'tmw_diff', 'aces_per_game_diff', 'df_per_game_diff',
       'bp_won_diff', 'wsp_diff', 'completeness_diff', 'serve_adv_diff',
       'elo_rating_diff'], dtype=object)

In [10]:
train_df.to_csv(os.path.abspath('../input/diff-cleaned-featured-2008-2017.csv'), index=False)